services:
  - type: web
    name: sundaraya-api
    plan: free
    region: singapore
    branch: main

    buildCommand: ./mvnw clean package
    startCommand: java -jar target/sundaraya_ref-0.0.1-SNAPSHOT.jar

    envVars:
      - key: PORT
        value: 8080   # Render overrides this with actual port
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://16.170.223.180:3306/new_dem
      - key: SPRING_DATASOURCE_USERNAME
        value: dbuser
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false   # secret → set manually in Render dashboard
      - key: JWT_SECRET
        sync: false   # secret
      - key: JWT_EXPIRATION
        value: 86400000
      - key: GOOGLE_MAPS_API_KEY
        sync: false   # secret
