services:
  - type: web
    name: sundaraya-api
    runtime: java
    plan: free
    region: singapore
    branch: main

    buildCommand: ./mvnw clean package
    startCommand: java -jar target/sundaraya_ref-0.0.1-SNAPSHOT.jar

    envVars:
      - key: PORT
        value: 8080   # Render will override this, but good to set default
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://16.170.223.180:3306/new_demo?allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&allowMultiQueries=true&useSSL=false
      - key: SPRING_DATASOURCE_USERNAME
        value: dbuser
      - key: SPRING_DATASOURCE_PASSWORD
        value: root@123
      - key: JWT_SECRET
        value: +H/oQqesV8NgkGHLAUfcFMR+7QL4dDPxjOsVFlMOe1o0JGDpisA5899sdcggUtt97sdcGC28KESAfT83BKAac/a25uyw==
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: GOOGLE_MAPS_API_KEY
        sync: false
